### ISSUE TITLE
Modal pop up on network error and local storage

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/quiz-renderer#2]
In the event that something goes wrong, which most likely is the wireless network is down, then a modal should pop up with something similar to "The quiz is unable to save your answers. Please ask for a paper version of the quiz and fill everything in on paper."

**Iain notes**

The only practical detail I’d offer from my experience is this: networks are always unreliable.  So your logic can never be to give up on the first failure, there should be some kind of retry.  And of course any kind of retry gives time for the student to make more changes which, in the event of a permanent outage, won’t get saved.  There are a bunch of ways to address this with the design (e.g. a green/yellow/red connection icon in the nav bar) to give some warning, but at the very least you should consider what number of retries you want and how long the page can go without contacting the server before it considers it a problem. 

In fact, it would be possible to use local storage and manifests to remove all communication with the HTTP server if you wanted.

**Comment by iainbryson** [comment]
Implemented.
