### ISSUE TITLE
Save your answers to your computer (as json)

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/quiz-renderer#3]
The bottom of the quiz page should have a "Hand in" button, and a "Save your answers to your computer" button.

Until the quiz website is approved as an official system, the students would need to upload their answers to the official exam server. So the button should be able to save the input to a json file without requiring a network connection.

The file should also contain meta data like

* name of student
* login name
* date
* quiz title
* save tim
* a checksum that the file is not corrupt

**Comment by iainbryson** [comment]
This is mostly implemented now, except for the checksum, login name and save time which will be quick to add.

**Comment by iainbryson** [comment]
Note that there are two ways to save: one from the main quiz page and a second from the "connection problem" dialog.  In fact, it's the only action someone can take from the connection problem dialog.
